name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.gradle
            ~/.m2/repository
          key: build-cache

      - name: Build
        run: ./gradlew build
